version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: application/docker/api/Dockerfile
    command: python conftest.py
    ports:
      - "9000:9000"
    volumes:
      - .:/code
