"""initial2

Revision ID: 13e8de2f932c
Revises: d50dc90e936b
Create Date: 2021-12-04 00:04:36.526387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13e8de2f932c'
down_revision = 'd50dc90e936b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
