"""initial3

Revision ID: aa1046f92691
Revises: 13e8de2f932c
Create Date: 2021-12-04 00:08:15.250347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa1046f92691'
down_revision = '13e8de2f932c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
