"""init1

Revision ID: bddf6d9daa74
Revises: 87bf6eb6deb1
Create Date: 2021-12-03 15:31:53.110300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bddf6d9daa74'
down_revision = '87bf6eb6deb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
