"""initial1

Revision ID: d50dc90e936b
Revises: 6c70e9309beb
Create Date: 2021-12-03 23:58:17.936954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd50dc90e936b'
down_revision = '6c70e9309beb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
